name: republic_on_volga
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.6
  firebase_crashlytics: ^2.0.2
  flutter_svg: ^0.19.0
  flutter_color: ^1.2.0
  infinity_page_view: ^1.0.0
  flutter_bloc: ^6.1.1
  date_range_picker: ^1.0.5
  url_launcher: ^5.7.10
  scroll_to_index: ^1.0.6
  youtube_player_flutter: ^7.0.0+7
  provider: ^4.3.3
  flutter_cache_manager: ^2.1.1
  html: ^0.14.0+3
  string_validator: ^0.1.4
  cached_network_image: ^2.2.0+1
  flutter_cache_store: ^0.7.2
  logger: ^0.9.4
  mime: ^0.9.7
  mime_type: ^0.3.2
  cupertino_icons: ^1.0.0
  built_value: ^8.0.4
  built_collection: ^5.0.0
  intl: ^0.17.0
  simple_html_css: ^3.0.1

module:
  androidX: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  lipsum: ^1.0.1
  build_runner: ^1.12.2
  built_value_generator: ^8.0.4
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

dependency_overrides:
  plugin_platform_interface: ^2.0.0
  convert: ^3.0.0
  crypto: ^3.0.0
  xml: ^5.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/news.svg
    - assets/command.svg
    - assets/partners.svg
    - assets/test.svg
    - assets/suvenirs.svg
    - assets/runes.svg
    - assets/archive.svg
    - assets/home.svg
    - assets/events.svg
    - assets/lection.svg
    - assets/filter.svg
    - assets/contacts.svg
    - assets/insta.svg
    - assets/banner.png
    - assets/logo.png
    - assets/A.png
    - assets/A_.png
    - assets/C.png
    - assets/C_.png
    - assets/CH.png
    - assets/E.png
    - assets/E_.png
    - assets/I.png
    - assets/I_.png
    - assets/K.png
    - assets/N.png
    - assets/O.webp
    - assets/P.png
    - assets/R.png
    - assets/SH.png
    - assets/T.png
    - assets/U.png
    - assets/V.webp
    - assets/W.png
    - assets/X.png
    - assets/Y.png
    - assets/YA.png
    - assets/YI.png
    - assets/lection_banner.png
    - assets/AL.webp
    - assets/Y_.png
    - assets/IYI.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
